const tours={
 'dont-smile':{title:'don’t smile at me tour',label:'LOS PRIMEROS ESCENARIOS',years:'2017',image:'https://slateandspirit.weebly.com/uploads/1/0/1/6/101603710/img-3340_orig.jpg',alt:'Billie Eilish en un concierto íntimo de sus primeros años',dates:'4 oct. — 2 nov. 2017',shows:'17 conciertos',regions:'Norteamérica · Europa',story:'La primera gira propia de Billie llevó las canciones de <strong>don’t smile at me</strong> desde pequeñas salas hasta nuevos públicos a ambos lados del Atlántico. Fue una etapa cercana y directa: la voz, las letras y la conexión con quienes ya seguían su música ocupaban el centro del espectáculo.',detail:'Entre octubre y noviembre de 2017, la gira pasó por Norteamérica y Europa. Con solo 17 conciertos, dejó ver el comienzo de una carrera que pronto saltaría a escenarios mucho mayores.',quote:'El primer capítulo: salas pequeñas, una voz imposible de confundir y un público que empezaba a crecer.',wiki:'https://en.wikipedia.org/wiki/Don%27t_Smile_at_Me_Tour',credit:'Slate & Spirit'},
 'wheres-mind':{title:'where’s my mind tour',label:'UNA VOZ QUE CRUZA EL ATLÁNTICO',years:'2018',image:'https://soundazed.s3.us-east-2.amazonaws.com/wp-content/uploads/2018/03/14013044/billie-eilish-review-soundazed-black-cat.jpg',alt:'Billie Eilish actuando en una sala durante su gira de 2018',dates:'14 feb. — 7 abr. 2018',shows:'28 conciertos',regions:'Europa · Norteamérica',story:'Con <strong>Where’s My Mind Tour</strong>, Billie volvió a la carretera en una etapa de crecimiento acelerado. Las canciones de su primer EP empezaban a viajar más lejos, pero el formato de sala todavía conservaba esa sensación de estar viendo algo muy personal.',detail:'La gira arrancó en febrero de 2018 y recorrió Europa y Norteamérica hasta abril. Sus 28 fechas marcaron un puente entre los primeros conciertos íntimos y una audiencia internacional cada vez mayor.',quote:'Una etapa de transición: la misma cercanía, con cada vez más gente cantando las canciones.',wiki:'https://en.wikipedia.org/wiki/Where%27s_My_Mind_Tour',credit:'Soundazed'},
 'one-by-one':{title:'1 by 1 tour',label:'CARA A CARA CON LOS FANS',years:'2018 — 2019',image:'https://s3-ap-southeast-2.amazonaws.com/savetonight/2018/11/40268884_274225943193659_8464796145690869760_n-1024x1022.jpg',alt:'Cartel de la gira 1 by 1 de Billie Eilish',dates:'20 oct. 2018 — 9 mar. 2019',shows:'44 conciertos',regions:'Norteamérica · Europa',story:'<strong>1 by 1</strong> llevó a Billie a un recorrido más amplio sin perder el contacto cercano que definía sus primeros conciertos. En esta gira convivían la intensidad de sus temas, su humor entre canciones y una comunidad de fans que crecía fecha tras fecha.',detail:'La ruta comenzó en Oakland en octubre de 2018 y terminó en Barcelona en marzo de 2019. Sus 44 conciertos pasaron por Norteamérica y Europa, en los meses previos a su primer álbum de estudio.',quote:'Una gira de salas que convirtió cada parada en un encuentro directo.',wiki:'https://en.wikipedia.org/wiki/1_by_1_Tour',credit:'SaveTonight'},
 'fall-asleep':{title:'when we all fall asleep tour',label:'DENTRO DEL MUNDO DE BILLIE',years:'2019',image:'https://cdn.prod.website-files.com/68667e91b7b98b8319fceff5/69aedd3ee1065c933d06a7ec_1609884703891.webp',fallback:'https://images.squarespace-cdn.com/content/v1/54b9e0c5e4b0d16cfa01a5d5/1738528354520-XVQUY9OVC7A6R1JKEMOC/Fury_BillieEilish_IndioCA_2019.jpg',alt:'Billie Eilish actuando con los visuales de su era de 2019',dates:'13 abr. — 17 nov. 2019',shows:'66 conciertos',regions:'Norteamérica · Europa · Oceanía',story:'Tras el lanzamiento de <strong>WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?</strong>, la gira convirtió el imaginario del álbum en un espectáculo: luces dramáticas, visuales inquietantes y canciones que alternaban vulnerabilidad y energía.',detail:'Comenzó en Coachella, en Indio, en abril de 2019. Después recorrió Norteamérica, Europa y Oceanía, y cerró en Ciudad de México en noviembre. Fue el salto de Billie a grandes escenarios internacionales.',quote:'Una pesadilla pop convertida en un universo visual propio.',wiki:'https://en.wikipedia.org/wiki/When_We_All_Fall_Asleep_Tour',credit:'Rich Fury'},
 'where-do-we-go':{title:'where do we go? world tour',label:'UNA GIRA QUE QUEDÓ EN PAUSA',years:'2020',image:'https://res.cloudinary.com/vectorworks/image/upload/f_auto%2Cq_auto/ja-JP/newsroom/articles/key-features-gdtf-mvr/03.09.2020_-_Billie_Eilish_-_WDWG_US_Tour_-_Miami_FL_-00943_JP-scaled.jpg',alt:'Billie Eilish en la puesta en escena de Where Do We Go? World Tour',dates:'9 — 12 mar. 2020',shows:'3 conciertos realizados',regions:'Norteamérica · interrumpida',story:'<strong>WHERE DO WE GO?</strong> se había concebido como una gran gira mundial, con una puesta en escena ambiciosa alrededor del álbum WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?. La propuesta incluía un escenario diseñado para acercar a Billie a todos los lados del público.',detail:'La gira arrancó en Miami el 9 de marzo de 2020. Solo pudieron celebrarse tres conciertos antes de que las fechas restantes se aplazaran por la pandemia; el recorrido terminó interrumpido en Raleigh.',quote:'Una historia breve en directo, marcada por una pausa que nadie había previsto.',wiki:'https://en.wikipedia.org/wiki/Where_Do_We_Go%3F_World_Tour',credit:'Vectorworks'},
 'happier':{title:'happier than ever world tour',label:'UN ESCENARIO PARA SENTIRLO TODO',years:'2022 — 2023',image:'https://momentfactory.com/cdn/shop/files/Moment_Factory_Happier_Than_Ever_Tour_22_44-WS.jpg?v=1715371081&width=1445',alt:'Billie Eilish en el escenario de Happier Than Ever, The World Tour',dates:'3 feb. 2022 — 2 abr. 2023',shows:'88 conciertos',regions:'5 continentes',story:'La gira de <strong>Happier Than Ever</strong> llevó el segundo álbum de Billie a un formato global. La producción combinó momentos íntimos con una energía enorme, y dejó espacio para que canciones tranquilas y explosivas compartieran el mismo escenario.',detail:'Comenzó en Nueva Orleans en febrero de 2022 y recorrió cinco continentes en seis tramos. El último concierto tuvo lugar en Guadalajara en abril de 2023.',quote:'Del susurro al desahogo: una noche que recorría todos los matices del álbum.',wiki:'https://en.wikipedia.org/wiki/Happier_Than_Ever,_The_World_Tour',credit:'Moment Factory'},
 'hmhas':{title:'HIT ME HARD AND SOFT: THE TOUR',label:'EL CAPÍTULO MÁS RECIENTE',years:'2024 — 2025',image:'https://assets.vogue.com/photos/6761d6e098b0165645e526c1/master/w_1024%2Cc_limit/GettyImages-2175574327.jpg',alt:'Billie Eilish durante HIT ME HARD AND SOFT: THE TOUR',dates:'29 sep. 2024 — 23 nov. 2025',shows:'106 conciertos',regions:'Asia · Europa · América · Oceanía',story:'Con <strong>HIT ME HARD AND SOFT: THE TOUR</strong>, Billie transformó su tercer álbum en una experiencia envolvente. El repertorio y el escenario recorren sus cambios de intensidad: momentos delicados, estallidos de energía y una conexión constante con el público.',detail:'La gira comenzó en Quebec en septiembre de 2024. Durante más de un año visitó Asia, Europa, Norteamérica y Oceanía, y concluyó en San Francisco en noviembre de 2025.',quote:'Una ola que va de lo suave a lo intenso, igual que el álbum que le da nombre.',wiki:'https://en.wikipedia.org/wiki/Hit_Me_Hard_and_Soft%3A_The_Tour',credit:'Vogue'}
};
const tourOrder=['dont-smile','wheres-mind','one-by-one','fall-asleep','where-do-we-go','happier','hmhas'];
const tourPaths={'dont-smile':'dont-smile-at-me.html','wheres-mind':'wheres-my-mind.html','one-by-one':'one-by-one.html','fall-asleep':'when-we-all-fall-asleep.html','where-do-we-go':'where-do-we-go.html','happier':'happier-than-ever.html','hmhas':'hit-me-hard-and-soft.html'};
const tourPalettes={'dont-smile':'ocean','wheres-mind':'ocean','one-by-one':'ocean','fall-asleep':'green','where-do-we-go':'green','happier':'gold','hmhas':'blue'};
const tourKey=document.body.dataset.tour;
const tour=tours[tourKey];
if(tour){
  document.title=`${tour.title} · Billie Verse`;
  document.body.dataset.tourPalette=tourPalettes[tourKey]||'green';
  const index=tourOrder.indexOf(tourKey);
  const previousKey=tourOrder[(index-1+tourOrder.length)%tourOrder.length];
  const nextKey=tourOrder[(index+1)%tourOrder.length];
  const previousTour=tours[previousKey], nextTour=tours[nextKey];
  document.querySelector('#tour-page').innerHTML=`<section class="hero"><div class="hero-media"><img src="${tour.image}" ${tour.fallback?`data-fallback="${tour.fallback}"`:''} alt="${tour.alt}" fetchpriority="high"></div><div class="hero-copy"><p class="eyebrow">${tour.label} · ${tour.years}</p><h1>${tour.title.replace(/(tour|TOUR)$/i,'<em>$1</em>')}</h1><p class="dek">Una mirada a una etapa de Billie Eilish en directo: cómo sonó, qué la hizo especial y dónde llevó su música.</p><div class="hero-meta"><span class="pill">${tour.dates}</span><span class="pill">${tour.shows}</span></div></div></section><section class="wrap facts fade"><div class="fact"><small>PERIODO</small><strong>${tour.dates}</strong></div><div class="fact"><small>CONCIERTOS</small><strong>${tour.shows}</strong></div><div class="fact"><small>RECORRIDO</small><strong>${tour.regions}</strong></div><div class="fact"><small>ERA</small><strong>${tour.years}</strong></div></section><section class="wrap story"><div class="fade"><p class="eyebrow">EL CONTEXTO</p><h2>Una etapa<br>en directo<span style="color:var(--green)">.</span></h2></div><div class="story-copy fade"><p>${tour.story}</p><p>${tour.detail}</p><div class="quote">${tour.quote}</div><p class="photo-credit">Imagen: ${tour.credit}. Consulta la fuente para conocer los créditos y contexto de la fotografía.</p></div></section><nav class="wrap tour-neighbors" aria-label="Navegar entre giras"><a class="neighbor-link" href="${tourPaths[previousKey]}"><small>← CAPÍTULO ANTERIOR</small><strong>${previousTour.title}</strong></a><a class="neighbor-index" href="../index.html#concerts">TODAS LAS GIRAS</a><a class="neighbor-link neighbor-next" href="${tourPaths[nextKey]}"><small>CAPÍTULO SIGUIENTE →</small><strong>${nextTour.title}</strong></a></nav><footer class="wrap end"><a class="all-dates" href="${tour.wiki}" target="_blank" rel="noreferrer">CONSULTAR TODAS LAS FECHAS Y RECINTOS <span>↗</span></a><a class="back" href="../index.html#concerts">← VOLVER A “UNA VIDA EN DIRECTO”</a></footer>`;
}
